name: Python Environment

on:
  # To run manually
  workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5
    
    - name: Install Python dependencies
      run: |
        python -m pip install matplotlib scipy

    - name: Hello World 
      run: |
        python -c "import scipy as sp; print('Scipy version: '+sp.__version__)"
        python -c "import matplotlib as mpl; print('Matplotlib version: '+mpl.__version__)"

# now has the winter of our discontent,
# been made glorious summer by this son of York.
